### ISSUE TITLE
[Bug]: `user` is nil in `redirect_next_step` of the `user_auth_controller` when access token is incorrect

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/server#399]
### What happened?

`user` is nil in `redirect_next_step` of the `user_auth_controller` when access token is incorrect.

### Version

alpha

### Relevant log output

```Shell
[info] GET /users/auth
[debug] Processing with IdentityWeb.UserAuthController.new/2
  Parameters: %{"login_challenge" => "3b9ce0e778bb481d90f77f498da0e835"}
  Pipelines: [:browser]
[debug] QUERY OK source="users" db=0.6ms queue=1.0ms idle=1427.5ms
SELECT u0."id", u0."first_name", u0."last_name", u0."email", u0."role", u0."inserted_at", u0."updated_at" FROM "users" AS u0 WHERE (u0."id" = $1) [1]
[info] Sent 500 in 256ms
[error] #PID<0.1247.0> running IdentityWeb.Endpoint (connection #PID<0.1246.0>, stream id 1) terminated
Server: localhost:4010 (http)
Request: GET /users/auth?login_challenge=3b9ce0e778bb481d90f77f498da0e835
** (exit) an exception was raised:
    ** (KeyError) key :role not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (identity_web 0.1.0) lib/identity_web/controllers/user_auth_controller.ex:32: IdentityWeb.UserAuthController.redirect_next_step/4
        (identity_web 0.1.0) lib/identity_web/controllers/user_auth_controller.ex:1: IdentityWeb.UserAuthController.action/2
        (identity_web 0.1.0) lib/identity_web/controllers/user_auth_controller.ex:1: IdentityWeb.UserAuthController.phoenix_controller_pipeline/2
        (phoenix 1.6.16) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (identity_web 0.1.0) lib/identity_web/endpoint.ex:1: IdentityWeb.Endpoint.plug_builder_call/2
        (identity_web 0.1.0) lib/plug/debugger.ex:136: IdentityWeb.Endpoint."call (overridable 3)"/2
        (identity_web 0.1.0) lib/identity_web/endpoint.ex:1: IdentityWeb.Endpoint.call/2
        (phoenix 1.6.16) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/jonas/dev/github.com/lenra-io/server/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/jonas/dev/github.com/lenra-io/server/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/jonas/dev/github.com/lenra-io/server/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

**Comment by jonas-martinez** [comment]
This happens during the `new` call in `user_auth_controller`. 
Here is the response body of the `HydraApi.get_login_request` line 126.
```elixir
%{
  "challenge" => "4c8303a91cd146f69ead3c5fbb3e3447",
  "client" => %{
    "owner" => "",
    "contacts" => [],
    "jwt_bearer_grant_access_token_lifespan" => nil,
    "logo_uri" => "",
    "jwks" => %{},
    "refresh_token_grant_refresh_token_lifespan" => nil,
    "request_object_signing_alg" => "RS256",
    "refresh_token_grant_id_token_lifespan" => nil,
    "grant_types" => ["authorization_code"],
    "updated_at" => "2023-08-07T07:27:13.897909Z",
    "created_at" => "2023-08-07T07:27:14Z",
    "client_uri" => "",
    "allowed_cors_origins" => [],
    "scope" => "manage:account manage:apps store resources",
    "refresh_token_grant_access_token_lifespan" => nil,
    "token_endpoint_auth_method" => "none",
    "authorization_code_grant_id_token_lifespan" => nil,
    "response_types" => ["code"],
    "userinfo_signed_response_alg" => "none",
    "client_id" => "139d06de-7d96-4880-a9c5-d3d1c4373829",
    "client_secret_expires_at" => 0,
    "client_credentials_grant_access_token_lifespan" => nil,
    "redirect_uris" => ["http://localhost:10000/redirect.html"],
    "tos_uri" => "",
    "metadata" => %{},
    "policy_uri" => "",
    "authorization_code_grant_refresh_token_lifespan" => nil,
    "subject_type" => "public",
    "authorization_code_grant_access_token_lifespan" => nil,
    "implicit_grant_access_token_lifespan" => nil,
    "audience" => [],
    "implicit_grant_id_token_lifespan" => nil,
    "client_name" => ""
  },
  "oidc_context" => %{},
  "request_url" => "http://localhost:4444/oauth2/auth?response_type=code&client_id=139d06de-7d96-4880-a9c5-d3d1c4373829&redirect_uri=http%3A%2F%2Flocalhost%3A10000%2Fredirect.html&scope=resources%20manage%3Aaccount%20store&state=0L4L713L3QFKMUBSG7LCH534H&code_challenge=MmXGxotDMjWseloubW1hPW03hy3jys_litg7uzjwITM&code_challenge_method=S256",
  "requested_access_token_audience" => [],
  "requested_scope" => ["resources", "manage:account", "store"],
  "session_id" => "08372379-b5f8-4c86-aa17-8eef3ebfd6cc",
  "skip" => true,
  "subject" => "1"
}
```

You can see that the `subject` is set to 1. I actually have no user in my DB because I just reset the DB with mix ecto.reset.
This error will not happen in production (or very rarely) because the DB will never be reset.

**Comment by Nesqwik** [comment]
You probably used a token from a previous launch, after the reset of the database.
We should add a check and return an error (401 ? 404 ?) if the subject doest not match any user.

This could happen in production if someone try to connect with a token bind to a deleted account.
