### ISSUE TITLE
[Bug]: MongoDB connection error throw randomly

### ISSUE THREAD

**Issue by shiipou** [lenra-io/server#561]
### What happened?

Sometimes, there a mongodb connection error that got thrown randomly when accessing Lenra server using `app.lenra.io`
We got that error multiple times a day, but not every days.

Mostly always thrown after this error : 
```bash
auth failed for user root: Authentication failed. 18
```

We need to check mongo logs before going futher.

### Version

1.5.3

### Relevant log output

```Shell
GenStateMachine #PID<0.3811.0> terminating
** (exit) exited in: GenServer.call(#PID<0.3727.0>, :get, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.4) lib/gen_server.ex:1030: GenServer.call/3
    (mongodb_driver 1.2.1) lib/mongo/auth.ex:34: Mongo.Auth.credentials/1
    (mongodb_driver 1.2.1) lib/mongo/auth.ex:20: Mongo.Auth.run/2
    (mongodb_driver 1.2.1) lib/mongo/mongo_db_connection.ex:114: Mongo.MongoDBConnection.connect/2
    (db_connection 2.6.0) lib/db_connection/connection.ex:92: DBConnection.Connection.handle_event/4
    (stdlib 3.17.2.4) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
    (stdlib 3.17.2.4) proc_lib.erl:236: :proc_lib.wake_up/3
State: Mongo.MongoDBConnection
Callback mode: :handle_event_function
Postponed events: []
Last event: {:internal, {:connect, :disconnect}}
Queued events: []
State: Mongo.MongoDBConnection
```

**Comment by taorepoara** [comment]
Might be a connection pool configuration problem.
